
const String back="Back";
const String history="History";
const String referral=' Referral ';
const String aboutUs=' About Us ';
const String setting =' Settings ';
const String helpAndSupport=' Help and Support ';
const String logout=' Logout ';
const String ANYWHEREYOUARE='Anywhere you are';
const String SELLHOUSESEASILY ="  Sell houses easily with the help of\nListenoryx and to make this line big\n              I am writing more.";
const String ATANYTIME= 'At anytime';
const String BOOKYOURCAR= 'Book your car';
const String SKIP="Skip";
const String RENTAL="Rental";
const  String WHEREWOULDYOUGO="Where would you go ?";
const String SELECTADDRESS="select address";
const String FORM="Form";
const String TO="To";
const String RECENTPLACE= "Recent place";