// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJrEny1fRzbNFIp09jsAHToJqp_M4VvXg',
    appId: '1:167104993030:web:3f2ed04462b9fa7d5ff087',
    messagingSenderId: '167104993030',
    projectId: 'management-notifications-566b9',
    authDomain: 'management-notifications-566b9.firebaseapp.com',
    storageBucket: 'management-notifications-566b9.appspot.com',
    measurementId: 'G-TS6T6REE1F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_hWqJMU3OfilElNthFuMNAzSnb3C7l4E',
    appId: '1:167104993030:android:177baa8ede353c515ff087',
    messagingSenderId: '167104993030',
    projectId: 'management-notifications-566b9',
    storageBucket: 'management-notifications-566b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPHzyFJ_vAb6d53kuJ5A_5yP-DAHx9tGM',
    appId: '1:167104993030:ios:ab40aa3f32e64c9d5ff087',
    messagingSenderId: '167104993030',
    projectId: 'management-notifications-566b9',
    storageBucket: 'management-notifications-566b9.appspot.com',
    androidClientId: '167104993030-5e30kiangrmmbe2earf756jbecb6isa9.apps.googleusercontent.com',
    iosClientId: '167104993030-7a5ood818g9ulr8h14okiajf4b1v1tla.apps.googleusercontent.com',
    iosBundleId: 'com.example.rentalCleanTdd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJrEny1fRzbNFIp09jsAHToJqp_M4VvXg',
    appId: '1:167104993030:web:3f2ed04462b9fa7d5ff087',
    messagingSenderId: '167104993030',
    projectId: 'management-notifications-566b9',
    authDomain: 'management-notifications-566b9.firebaseapp.com',
    storageBucket: 'management-notifications-566b9.appspot.com',
    measurementId: 'G-TS6T6REE1F',
  );
}
